import { ReactNode } from "react";
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/Components/Navbar/Navbar";
import AnimatedHeroSectionBackground from "../Components/Home/AnimatedHeroSectionBackground";

export const metadata: Metadata = {
  title: "CricMarket",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: ReactNode;
}>) => {
  return (
    <html lang="en" className=" dark bg-background">
      <body className="antialiased space-grotesk h-screen">
        <AnimatedHeroSectionBackground />
        <Navbar />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
